/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  ExecutableScript,
  ExecuteScriptParams,
  ExecuteScriptResult,
  Script,
  SignerProvider,
  HexString,
} from "@alephium/web3";
import { getContractByCodeHash } from "./contracts";
import { default as PlaceBetScriptJson } from "../PlaceBet.ral.json";

export const PlaceBet = new ExecutableScript<{
  electionStake: HexString;
  candidate: boolean;
  amount: bigint;
}>(Script.fromJson(PlaceBetScriptJson, "", []), getContractByCodeHash);
